#!/usr/bin/env bash

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 \"<title>\"" >&2
  exit 1
fi

title="$1"
filename_title="${title//・/-}"
filename_title="${filename_title// /_}"

filename="_posts/$(date +%Y-%m-%d)-$(date +%H%M%S).${$}.${filename_title}.markdown"

cat > "$filename" <<PTEMPLATE
---
layout: post
category: uncategorized
title: "${title}"
---
PTEMPLATE

#vim "$filename"

echo "$filename"

