#!/bin/bash

if [ "$#" -ne 1 ] ; then
  echo "Usage: $0 \"<title>\"" >&2
  exit 1
fi

filename="_posts/`date +%Y-%m-%d-"${1}".markdown`"
filename=${filename//" "/"_"}

cat > $filename <<PTEMPLATE
---
layout: post
category: Uncategorized
title: "${1}"
---

PTEMPLATE

vim ${filename}
