---

name: makepost
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  makepost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate and Commit Posts
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          chmod 755 ./mkpost
          $(/usr/bin/env bash) ./mkpost "untitled"
          git add _posts
          git commit -m "Auto commit: $(date)" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

